services:
  # Container for postgresql database
  postgres:
    container_name: container-pg
    image: postgres:17
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # Container for pgadmin dashboard
  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4:8
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

# Define persistant storage
volumes:
  postgres-data:
